baseURL: "https://scebotari66.github.io/"
languageCode: "en-us"
title: "One line at a time"
theme: "ghostwriter"

author:
  name: "Serghei Cebotari"

params:
  name: "Serghei Cebotari"
  github: "https://github.com/scebotari66"
  twitter: "https://twitter.com/scebotari66"
  stackoverflow: "https://stackoverflow.com/users/384676/scebotari66"
  email: cebotariserghei@gmail.com

permalinks:
  post: "/:year/:month/:day/:title"

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Uses
      url: /uses
      weight: 2